#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const GENERATED_MARKER = 'Generated by Nova Expo Workflow Toolkit';

function parseArguments(argumentsList) {
  const [action, ...rest] = argumentsList;
  const options = {};
  for (let index = 0; index < rest.length; index += 1) {
    const argument = rest[index];
    if (!argument.startsWith('--')) throw new Error(`Unexpected argument: ${argument}`);
    const equals = argument.indexOf('=');
    if (equals !== -1) {
      options[argument.slice(2, equals)] = argument.slice(equals + 1);
    } else if (rest[index + 1] && !rest[index + 1].startsWith('--')) {
      options[argument.slice(2)] = rest[index + 1];
      index += 1;
    } else {
      options[argument.slice(2)] = true;
    }
  }
  return { action, options };
}

function readJson(filename, fallback) {
  if (!fs.existsSync(filename)) return fallback;
  return JSON.parse(fs.readFileSync(filename, 'utf8'));
}

function writeFile(filename, contents, dryRun) {
  const relative = path.relative(process.cwd(), filename) || path.basename(filename);
  if (dryRun) {
    process.stdout.write(`[dry-run] write ${relative}\n`);
    return;
  }
  fs.mkdirSync(path.dirname(filename), { recursive: true });
  fs.writeFileSync(filename, contents);
  process.stdout.write(`wrote ${relative}\n`);
}

function writeJson(filename, value, dryRun) {
  writeFile(filename, `${JSON.stringify(value, null, 2)}\n`, dryRun);
}

function assertProject(projectDirectory) {
  const packagePath = path.join(projectDirectory, 'package.json');
  const manifest = readJson(packagePath);
  if (!manifest || !(manifest.dependencies?.expo || manifest.devDependencies?.expo)) {
    throw new Error(`Not an Expo project: ${projectDirectory}`);
  }
  return manifest;
}

function appConfig(projectDirectory) {
  const filename = path.join(projectDirectory, 'app.json');
  const config = readJson(filename);
  if (!config) throw new Error('app.json is required for automatic setup');
  return { config, expo: config.expo || config, filename };
}

function validateAppIdentifier(value) {
  if (!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(value)) {
    throw new Error('The application identifier must use reverse-domain format, for example com.acme.myapp');
  }
}

function mergeProfile(existing, additions) {
  return { ...(existing || {}), ...additions, env: { ...(existing?.env || {}), ...(additions.env || {}) } };
}

function configureVariants(projectDirectory, options, dryRun) {
  const manifest = assertProject(projectDirectory);
  const { expo } = appConfig(projectDirectory);
  const dynamicPath = path.join(projectDirectory, 'app.config.js');
  if (manifest.type === 'module') {
    throw new Error('Automatic variant generation currently requires a CommonJS Expo config; this project declares package.json type=module');
  }
  const otherDynamicConfig = ['app.config.ts', 'app.config.mjs', 'app.config.cjs']
    .map((name) => path.join(projectDirectory, name))
    .find((filename) => fs.existsSync(filename));
  if (otherDynamicConfig) {
    throw new Error(`${path.basename(otherDynamicConfig)} already exists; merge variants manually to preserve custom logic`);
  }
  if (fs.existsSync(dynamicPath)) {
    const existing = fs.readFileSync(dynamicPath, 'utf8');
    if (!existing.includes(GENERATED_MARKER)) {
      throw new Error('app.config.js already exists and was not generated by Nova; merge variants manually to preserve custom logic');
    }
  }

  const productionAndroidId = options['app-id'] || expo.android?.package || expo.ios?.bundleIdentifier;
  const productionIosId = options['app-id'] || expo.ios?.bundleIdentifier || expo.android?.package;
  if (!productionAndroidId || !productionIosId) throw new Error('--app-id is required because app.json has no Android/iOS application identifier');
  validateAppIdentifier(productionAndroidId);
  validateAppIdentifier(productionIosId);
  const name = options.name || expo.name || manifest.name;
  const baseScheme = String(expo.scheme || expo.slug || manifest.name).replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
  const developmentSuffix = options['development-suffix'] || '.dev';
  const previewSuffix = options['preview-suffix'] || '.preview';

  const variants = {
    development: {
      name: `${name} (Dev)`,
      androidIdentifier: `${productionAndroidId}${developmentSuffix}`,
      iosIdentifier: `${productionIosId}${developmentSuffix}`,
      scheme: `${baseScheme}dev`,
    },
    preview: {
      name: `${name} (Preview)`,
      androidIdentifier: `${productionAndroidId}${previewSuffix}`,
      iosIdentifier: `${productionIosId}${previewSuffix}`,
      scheme: `${baseScheme}preview`,
    },
    production: {
      name,
      androidIdentifier: productionAndroidId,
      iosIdentifier: productionIosId,
      scheme: baseScheme,
    },
  };

  for (const variant of Object.values(variants)) {
    validateAppIdentifier(variant.androidIdentifier);
    validateAppIdentifier(variant.iosIdentifier);
  }

  const dynamicConfig = `// ${GENERATED_MARKER}\nconst variants = ${JSON.stringify(variants, null, 2)};\n\nmodule.exports = ({ config }) => {\n  const variant = process.env.APP_VARIANT || 'production';\n  const selected = variants[variant] || variants.production;\n  const expo = config;\n\n  return {\n    ...expo,\n    name: selected.name,\n    scheme: selected.scheme,\n    runtimeVersion: expo.runtimeVersion || { policy: 'fingerprint' },\n    android: { ...(expo.android || {}), package: selected.androidIdentifier },\n    ios: { ...(expo.ios || {}), bundleIdentifier: selected.iosIdentifier },\n    extra: { ...(expo.extra || {}), novaVariant: variant },\n  };\n};\n`;
  writeFile(dynamicPath, dynamicConfig, dryRun);

  const easPath = path.join(projectDirectory, 'eas.json');
  const eas = readJson(easPath, { cli: { appVersionSource: 'remote' }, build: {}, submit: {} });
  eas.build ||= {};
  eas.submit ||= {};
  eas.build.development = mergeProfile(eas.build.development, {
    developmentClient: true,
    distribution: 'internal',
    channel: 'development',
    environment: 'development',
    env: { APP_VARIANT: 'development' },
  });
  eas.build.preview = mergeProfile(eas.build.preview, {
    distribution: 'internal',
    channel: 'preview',
    environment: 'preview',
    env: { APP_VARIANT: 'preview' },
  });
  eas.build.production = mergeProfile(eas.build.production, {
    distribution: 'store',
    channel: 'production',
    environment: 'production',
    env: { APP_VARIANT: 'production' },
  });
  eas.build['e2e-test'] = mergeProfile(eas.build['e2e-test'] || { extends: 'preview' }, {
    withoutCredentials: true,
    environment: 'preview',
    env: { APP_VARIANT: 'preview' },
    android: { buildType: 'apk', ...(eas.build['e2e-test']?.android || {}) },
    ios: { simulator: true, ...(eas.build['e2e-test']?.ios || {}) },
  });
  eas.submit.production = { ...(eas.submit.production || {}) };
  writeJson(easPath, eas, dryRun);
  process.stdout.write(`Configured development, preview, production, and e2e-test variants for ${productionAndroidId}.\n`);
}

function configureMetadata(projectDirectory, options, dryRun) {
  assertProject(projectDirectory);
  const { expo } = appConfig(projectDirectory);
  const metadataPath = path.join(projectDirectory, 'store.config.json');
  if (fs.existsSync(metadataPath) && !options.force) {
    throw new Error('store.config.json already exists; use --force only if replacing it is intentional');
  }
  const title = options.title || expo.name;
  const supportUrl = options['support-url'];
  const privacyPolicyUrl = options['privacy-url'];
  if (!title || !supportUrl || !privacyPolicyUrl) {
    throw new Error('--title, --support-url, and --privacy-url are required');
  }
  for (const [label, value] of [['support URL', supportUrl], ['privacy URL', privacyPolicyUrl], ['marketing URL', options['marketing-url']]]) {
    if (!value) continue;
    try {
      const parsed = new URL(value);
      if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error();
    } catch {
      throw new Error(`${label} must be a valid http(s) URL`);
    }
  }
  const info = {
    title,
    subtitle: options.subtitle || undefined,
    description: options.description || `${title} mobile application.`,
    keywords: String(options.keywords || '').split(',').map((item) => item.trim()).filter(Boolean),
    marketingUrl: options['marketing-url'] || supportUrl,
    supportUrl,
    privacyPolicyUrl,
  };
  writeJson(metadataPath, { configVersion: 0, apple: { info: { 'en-US': info } } }, dryRun);

  const easPath = path.join(projectDirectory, 'eas.json');
  const eas = readJson(easPath, { build: {}, submit: {} });
  eas.submit ||= {};
  eas.submit.production ||= {};
  eas.submit.production.ios = { ...(eas.submit.production.ios || {}), metadataPath: './store.config.json' };
  writeJson(easPath, eas, dryRun);
}

function configureNotifications(projectDirectory, options, dryRun) {
  assertProject(projectDirectory);
  const { config, expo, filename } = appConfig(projectDirectory);
  const plugins = Array.isArray(expo.plugins) ? expo.plugins : [];
  if (!plugins.some((plugin) => plugin === 'expo-notifications' || (Array.isArray(plugin) && plugin[0] === 'expo-notifications'))) {
    plugins.push('expo-notifications');
    expo.plugins = plugins;
    writeJson(filename, config, dryRun);
  }

  const servicePath = path.join(projectDirectory, 'src/services/notifications/index.ts');
  if (fs.existsSync(servicePath)) {
    const existing = fs.readFileSync(servicePath, 'utf8');
    if (!existing.includes(GENERATED_MARKER) && !options.force) {
      throw new Error('src/services/notifications/index.ts already contains custom code; refusing to replace it');
    }
  }
  const service = `// ${GENERATED_MARKER}\nimport Constants from 'expo-constants';\nimport * as Device from 'expo-device';\nimport * as Notifications from 'expo-notifications';\nimport { Platform } from 'react-native';\n\nexport function configureNotificationHandling(): void {\n  Notifications.setNotificationHandler({\n    handleNotification: async () => ({\n      shouldPlaySound: true,\n      shouldSetBadge: false,\n      shouldShowBanner: true,\n      shouldShowList: true,\n    }),\n  });\n}\n\nexport async function registerForPushNotifications(): Promise<string> {\n  if (!Device.isDevice) {\n    throw new Error('Push notifications require a physical device or supported simulator.');\n  }\n\n  if (Platform.OS === 'android') {\n    await Notifications.setNotificationChannelAsync('default', {\n      name: 'Default',\n      importance: Notifications.AndroidImportance.DEFAULT,\n    });\n  }\n\n  const current = await Notifications.getPermissionsAsync();\n  const permission = current.status === 'granted'\n    ? current\n    : await Notifications.requestPermissionsAsync();\n  if (permission.status !== 'granted') {\n    throw new Error('Notification permission was not granted.');\n  }\n\n  const projectId = Constants.easConfig?.projectId ?? Constants.expoConfig?.extra?.eas?.projectId;\n  if (!projectId) {\n    throw new Error('EAS project ID is missing. Link the app with eas project:init first.');\n  }\n\n  return (await Notifications.getExpoPushTokenAsync({ projectId })).data;\n}\n`;
  writeFile(servicePath, service, dryRun);
  process.stdout.write('Notification client setup is ready. Configure FCM/APNs credentials before building.\n');
}

function main() {
  const { action, options } = parseArguments(process.argv.slice(2));
  const projectDirectory = path.resolve(options.project || process.cwd());
  const dryRun = process.env.EXPO_TOOLKIT_DRY_RUN === '1' || options['dry-run'];
  if (action === 'variants') configureVariants(projectDirectory, options, dryRun);
  else if (action === 'metadata') configureMetadata(projectDirectory, options, dryRun);
  else if (action === 'notifications') configureNotifications(projectDirectory, options, dryRun);
  else throw new Error(`Unknown project configuration action: ${action || '(missing)'}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    process.stderr.write(`error: ${error.message}\n`);
    process.exitCode = 1;
  }
}

module.exports = { configureMetadata, configureNotifications, configureVariants, parseArguments };
