#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

function readJson(filename) {
  if (!fs.existsSync(filename)) return null;
  return JSON.parse(fs.readFileSync(filename, 'utf8'));
}

function parseArguments(argumentsList) {
  const options = {};
  for (let index = 0; index < argumentsList.length; index += 1) {
    const argument = argumentsList[index];
    if (!argument.startsWith('--')) throw new Error(`Unexpected argument: ${argument}`);
    const key = argument.slice(2);
    if (argumentsList[index + 1] && !argumentsList[index + 1].startsWith('--')) {
      options[key] = argumentsList[index + 1];
      index += 1;
    } else options[key] = true;
  }
  return options;
}

function audit(projectDirectory, options) {
  const failures = [];
  const warnings = [];
  const pass = (message) => process.stdout.write(`✓ ${message}\n`);
  const manifest = readJson(path.join(projectDirectory, 'package.json'));
  const app = readJson(path.join(projectDirectory, 'app.json'));
  const eas = readJson(path.join(projectDirectory, 'eas.json'));
  const expo = app?.expo || app;
  const profile = options.profile || 'production';
  const kind = options.kind || 'build';

  if (!manifest?.dependencies?.expo && !manifest?.devDependencies?.expo) failures.push('package.json does not declare Expo');
  else pass('Expo dependency is declared');
  if (!expo) failures.push('app.json is missing or invalid');
  if (!expo?.android?.package) failures.push('android.package is missing from app.json');
  else pass(`Android application ID: ${expo.android.package}`);
  if (!expo?.ios?.bundleIdentifier) failures.push('ios.bundleIdentifier is missing from app.json');
  else pass(`iOS bundle identifier: ${expo.ios.bundleIdentifier}`);
  if (!eas?.build?.[profile]) failures.push(`EAS build profile '${profile}' is missing`);
  else {
    pass(`EAS build profile '${profile}' exists`);
    if (!eas.build[profile].environment) warnings.push(`build profile '${profile}' does not explicitly select an EAS environment`);
    if (!eas.build[profile].channel) warnings.push(`build profile '${profile}' does not explicitly select an update channel`);
  }
  if (kind === 'submit' && !eas?.submit?.[profile]) failures.push(`EAS submit profile '${profile}' is missing`);
  if (kind === 'submit' && !fs.existsSync(path.join(projectDirectory, 'store.config.json'))) {
    warnings.push('store.config.json is missing; app-store metadata must be completed manually');
  }
  if (kind === 'update') {
    const dynamicPath = path.join(projectDirectory, 'app.config.js');
    const dynamic = fs.existsSync(dynamicPath) ? fs.readFileSync(dynamicPath, 'utf8') : '';
    const fingerprintPolicy = expo?.runtimeVersion?.policy === 'fingerprint' ||
      (dynamic.includes('Generated by Nova Expo Workflow Toolkit') && dynamic.includes("policy: 'fingerprint'"));
    if (!fingerprintPolicy) failures.push('OTA updates require runtimeVersion.policy=fingerprint for Nova release safety');
    else pass('Fingerprint runtime policy protects native/update compatibility');
  }
  if (!manifest?.scripts?.validate) warnings.push('package.json has no combined validate script');
  else pass('Project validation script is available');

  for (const warning of warnings) process.stderr.write(`! ${warning}\n`);
  for (const failure of failures) process.stderr.write(`✗ ${failure}\n`);
  if (failures.length) throw new Error(`${failures.length} release requirement(s) failed`);
}

if (require.main === module) {
  try {
    const options = parseArguments(process.argv.slice(2));
    audit(path.resolve(options.project || process.cwd()), options);
  } catch (error) {
    process.stderr.write(`error: ${error.message}\n`);
    process.exitCode = 1;
  }
}

module.exports = { audit, parseArguments };
