name: Preview builds

on:
  workflow_dispatch: {}

jobs:
  fingerprint:
    name: Fingerprint native projects
    type: fingerprint
    environment: preview

  get_android_build:
    name: Find compatible Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: preview

  get_ios_build:
    name: Find compatible iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: preview

  build_android:
    name: Build Android preview
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS preview
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: preview
