#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE="$(mktemp -d "${TMPDIR:-/tmp}/expo-toolkit-test.XXXXXX")"
trap 'rm -rf "$FIXTURE"' EXIT

printf '%s\n' '{"name":"fixture","dependencies":{"expo":"^57.0.0"}}' > "$FIXTURE/package.json"
printf '%s\n' '{"expo":{"name":"Fixture App","slug":"fixture-app","scheme":"fixtureapp","android":{"package":"com.example.fixture"},"ios":{"bundleIdentifier":"com.example.fixture"}}}' > "$FIXTURE/app.json"
printf '%s\n' '{"build":{"development":{"developmentClient":true},"preview":{"distribution":"internal"},"production":{"distribution":"store"}},"submit":{"production":{}}}' > "$FIXTURE/eas.json"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

assert_contains() {
  local output="$1"
  local expected="$2"
  [[ "$output" == *"$expected"* ]] || fail "expected '$expected' in '$output'"
}

assert_not_contains() {
  local output="$1"
  local unexpected="$2"
  [[ "$output" != *"$unexpected"* ]] || fail "did not expect '$unexpected' in '$output'"
}

for script in "$ROOT"/*.sh "$ROOT"/lib/*.sh; do
  bash -n "$script"
done

base_env=(
  EXPO_TOOLKIT_DRY_RUN=1
  EXPO_TOOLKIT_EXPO_BIN=expo-test
  EXPO_TOOLKIT_EAS_BIN=eas-test
)

ln -s "$ROOT/run.sh" "$FIXTURE/nova-workflows"
output="$("$FIXTURE/nova-workflows" --version)"
assert_contains "$output" "$(node -p "require('$ROOT/package.json').version")"

output="$(PROJECT_DIR="$FIXTURE" bash -c 'source "$1/lib/tui.sh"; tui_initialize "$2" "$1" 1; tui_header' _ "$ROOT" "$FIXTURE")"
assert_contains "$output" "NOVA  / EXPO WORKFLOWS"
assert_contains "$output" "Fixture App"

output="$(env "${base_env[@]}" "$ROOT/dev.sh" web --project "$FIXTURE" --clear)"
assert_contains "$output" "+ expo-test start --web --clear"

output="$(env "${base_env[@]}" EXPO_PLATFORM=android EAS_PROFILE=preview "$ROOT/build.sh" create --project "$FIXTURE")"
assert_contains "$output" "+ eas-test build --platform android --profile preview"

output="$(env "${base_env[@]}" EAS_UPDATE_CHANNEL=preview EAS_UPDATE_MESSAGE='test update' "$ROOT/update.sh" publish --project "$FIXTURE")"
assert_contains "$output" "+ eas-test update --channel preview --message test\\ update"
assert_contains "$output" "--environment preview"

output="$(env "${base_env[@]}" "$ROOT/release-check.sh" update --project "$FIXTURE" --profile preview --platform android --environment staging)"
assert_contains "$output" "+ eas-test fingerprint:generate --platform android --environment staging --non-interactive"

output="$(env "${base_env[@]}" "$ROOT/workflow.sh" run --project "$FIXTURE" release.yml -F version=1.2.3)"
assert_contains "$output" "+ eas-test workflow:run .eas/workflows/release.yml -F version=1.2.3"

output="$(env "${base_env[@]}" EAS_ENVIRONMENT=production "$ROOT/env.sh" list --project "$FIXTURE" --json)"
assert_contains "$output" "+ eas-test env:list production --json"

output="$(env "${base_env[@]}" "$ROOT/expo.sh" --project "$FIXTURE" -- export --platform web)"
assert_contains "$output" "+ expo-test export --platform web"

output="$(env "${base_env[@]}" "$ROOT/workflow.sh" --project "$FIXTURE")"
assert_contains "$output" "+ eas-test workflow:runs"

output="$(env "${base_env[@]}" "$ROOT/version.sh" status --project "$ROOT")"
assert_contains "$output" "Expo compatibility was skipped"
assert_contains "$output" "Compatibility checks passed"

output="$(NOVA_VSCODE_BIN=/usr/bin/true "$ROOT/run.sh" gui --project "$FIXTURE")"
assert_contains "$output" "VS Code opened"

output="$(printf '9\n' | env "${base_env[@]}" EXPO_TOOLKIT_NO_PAUSE=1 "$ROOT/run.sh" --project "$FIXTURE")"
assert_contains "$output" "Expo Workflow Assistant"
assert_contains "$output" "Goodbye."

output="$(printf '1\n1\n9\n' | env "${base_env[@]}" EXPO_TOOLKIT_NO_PAUSE=1 "$ROOT/run.sh" --project "$FIXTURE")"
assert_contains "$output" "Project health check"
assert_contains "$output" "+ expo-test install --check"

output="$(printf '1\n1\n9\n' | env "${base_env[@]}" EXPO_TOOLKIT_DRY_RUN=0 EXPO_TOOLKIT_EXPO_BIN=/usr/bin/false EXPO_TOOLKIT_NO_PAUSE=1 "$ROOT/run.sh" --project "$FIXTURE" 2>&1)"
assert_contains "$output" "did not complete"
assert_contains "$output" "Goodbye."

output="$(env "${base_env[@]}" "$ROOT/env.sh" set --project "$FIXTURE" development --name API_KEY --value super-secret --visibility secret)"
assert_contains "$output" "--value \*\*\*"
assert_not_contains "$output" "super-secret"

output="$(printf '6\n2\n1\nAPI_KEY\n3\nsuper-secret\n9\n' | env "${base_env[@]}" EXPO_TOOLKIT_NO_PAUSE=1 "$ROOT/run.sh" --project "$FIXTURE" 2>&1)"
assert_contains "$output" "Save API_KEY completed"
assert_not_contains "$output" "super-secret"

EXPO_TOOLKIT_DRY_RUN=0 "$ROOT/variants.sh" setup --project "$FIXTURE"
assert_contains "$(sed -n '1,80p' "$FIXTURE/app.config.js")" "Generated by Nova Expo Workflow Toolkit"
assert_contains "$(sed -n '1,80p' "$FIXTURE/app.config.js")" "module.exports = ({ config })"
assert_not_contains "$(sed -n '1,80p' "$FIXTURE/app.config.js")" "require('./app.json')"
assert_contains "$(node -p "require('$FIXTURE/eas.json').build.preview.channel")" "preview"
assert_contains "$(node -p "require('$FIXTURE/eas.json').build['e2e-test'].environment")" "preview"
assert_contains "$(node -p "require('$FIXTURE/eas.json').build['e2e-test'].withoutCredentials")" "true"
assert_contains "$(cd "$FIXTURE" && APP_VARIANT=preview node -p "require('./app.config.js')({ config: require('./app.json').expo }).android.package")" "com.example.fixture.preview"

EXPO_TOOLKIT_DRY_RUN=0 "$ROOT/workflow-templates.sh" install --project "$FIXTURE"
[[ -f "$FIXTURE/.eas/workflows/production.yml" ]] || fail "production workflow was not installed"
assert_contains "$(sed -n '1,5p' "$FIXTURE/.maestro/home.yml")" "com.example.fixture.preview"

output="$(env "${base_env[@]}" "$ROOT/workflow-templates.sh" install --project "$FIXTURE" --validate)"
assert_contains "$output" "+ eas-test workflow:validate"
assert_contains "$output" ".eas/workflows/production.yml"

node "$ROOT/lib/project-config.js" notifications --project "$FIXTURE"
assert_contains "$(sed -n '1,20p' "$FIXTURE/src/services/notifications/index.ts")" "registerForPushNotifications"

node "$ROOT/lib/project-config.js" metadata --project "$FIXTURE" --title "Fixture App" --support-url "https://example.com/support" --privacy-url "https://example.com/privacy"
assert_contains "$(node -p "require('$FIXTURE/store.config.json').apple.info['en-US'].privacyPolicyUrl")" "https://example.com/privacy"

node "$ROOT/lib/release-audit.js" --project "$FIXTURE" --kind build --profile production
node "$ROOT/lib/release-audit.js" --project "$FIXTURE" --kind submit --profile production
node "$ROOT/lib/release-audit.js" --project "$FIXTURE" --kind update --profile production

printf 'All workflow contract tests passed.\n'
