import type { ExpoProjectInfo } from '../projectInfo';
import {
  toDefaultAppIdentifier,
  validateAppIdentifier,
  validateDisplayName,
} from '../projectCreation';
import type { ToolkitAction } from '../toolkitCatalog';
import type { CommandContext } from './context';

const CLOUD_CATEGORIES = new Set(['builds', 'updates', 'release', 'cloud']);

/** Sentinels for catalog choices that stand for something other than a literal value. */
const ALL_UPDATE_BRANCHES = '__nova_all_update_branches__';
const CUSTOM_UPDATE_BRANCH = '__nova_custom_update_branch__';
/** Marks a pick value as a channel name rather than a branch name. */
const CHANNEL_PREFIX = 'channel:';
const CUSTOM_ENVIRONMENT = '__nova_custom_environment__';

function validateUrl(value: string): string | undefined {
  try {
    const url = new URL(value);
    return ['http:', 'https:'].includes(url.protocol) ? undefined : 'Use an http or https URL.';
  } catch {
    return 'Enter a complete URL, such as https://example.com/support.';
  }
}

/**
 * Collects the values a catalog workflow needs before it runs, so the script
 * itself never has to prompt on a TTY the dashboard does not have. Each block
 * is keyed by action id and appends to the catalog's own base arguments.
 *
 * Returns `undefined` when the user cancels or when a precondition fails, and
 * the caller must then run nothing at all.
 */
export async function prepareToolkitAction(
  context: CommandContext,
  action: ToolkitAction,
  project: ExpoProjectInfo,
): Promise<string[] | undefined> {
  const {
    dashboard,
    askValidated,
    pickPlatform,
    pickProfile,
    requireEasProject,
    validateRequiredText,
  } = context;
  if (CLOUD_CATEGORIES.has(action.category) && !(await requireEasProject(project)))
    return undefined;
  const args = [...action.args];
  const buildProfileNames = () => project.buildProfiles.map((item) => item.name);

  if (action.id === 'development.variants') {
    // A dynamic config Nova generated is regenerated from the same inputs, so
    // re-running variant setup on it is safe; anyone else's is not.
    if (project.configFile && project.configFile !== 'app.json' && !project.hasGeneratedConfig) {
      await dashboard.showFeedback(
        'error',
        'Variants cannot rewrite this Expo config',
        `Nova will not overwrite or merge ${project.configFile}, because it was not generated by Nova and may contain logic this workflow cannot reproduce. Configure variants by hand to preserve it.`,
        { label: 'Open configuration', command: 'novaExpo.project.openConfig' },
      );
      return undefined;
    }
    if (!project.androidPackage && !project.iosBundleIdentifier) {
      const appId = await askValidated(
        'Production application identifier',
        project.slug ? toDefaultAppIdentifier(project.slug) : 'com.example.app',
        'This becomes the base Android package and iOS bundle identifier.',
        validateAppIdentifier,
      );
      if (!appId) return undefined;
      args.push('--app-id', appId);
    }
  }

  if (action.id === 'project.templates') {
    let previewId = project.androidPackage ? `${project.androidPackage}.preview` : undefined;
    if (!previewId) {
      previewId = await askValidated(
        'Preview application identifier',
        project.slug
          ? `${toDefaultAppIdentifier(project.slug)}.preview`
          : 'com.example.app.preview',
        'Maestro uses this identifier to launch the preview build.',
        validateAppIdentifier,
      );
    }
    if (!previewId) return undefined;
    args.push('--app-id', previewId);
  }

  if (['development.notification-credentials', 'release.credentials'].includes(action.id)) {
    const platform = await pickPlatform('Choose a credential platform', false);
    if (!platform) return undefined;
    args.push('--platform', platform);
  }

  if (['builds.versions', 'builds.sync-versions'].includes(action.id)) {
    if (project.buildProfiles.length === 0) {
      await dashboard.showFeedback(
        'warning',
        'No build profiles found',
        'Add a build profile to eas.json before reading or synchronizing app versions.',
      );
      return undefined;
    }
    const platform = await pickPlatform('Choose a platform', false);
    if (!platform) return undefined;
    const profile = await pickProfile('Choose an EAS build profile', buildProfileNames());
    if (!profile) return undefined;
    args.push('--platform', platform, '--profile', profile);
  }

  if (action.id === 'updates.fingerprint') {
    if (project.buildProfiles.length === 0) {
      await dashboard.showFeedback(
        'warning',
        'No build profiles found',
        'Add a build profile to eas.json before generating a build-profile fingerprint.',
      );
      return undefined;
    }
    const platform = await pickPlatform('Choose a fingerprint platform', false);
    if (!platform) return undefined;
    const profile = await pickProfile('Choose an EAS build profile', buildProfileNames());
    if (!profile) return undefined;
    args.push('--platform', platform, '--build-profile', profile);
  }

  if (action.id === 'updates.list') {
    // A channel and a branch are different EAS objects that only coincide by
    // convention, so a name detected from a build profile is passed back as the
    // channel it is. Sending it as `--branch` silently returned nothing
    // whenever a project had mapped a channel to a differently named branch.
    const channels = [
      ...new Set(project.buildProfiles.map((item) => item.channel).filter(Boolean)),
    ] as string[];
    const scopeChoice = await dashboard.pick('Choose which updates to list', [
      {
        label: 'All branches',
        description: 'List updates across every branch',
        value: ALL_UPDATE_BRANCHES,
      },
      ...channels.map((name) => ({
        label: name,
        description: 'Channel detected from an EAS build profile',
        detail: 'Lists the updates this channel currently serves',
        value: `${CHANNEL_PREFIX}${name}`,
      })),
      {
        label: 'Enter a branch name…',
        description: 'Use an EAS Update branch not detected locally',
        value: CUSTOM_UPDATE_BRANCH,
      },
    ]);
    if (!scopeChoice) return undefined;
    if (scopeChoice === ALL_UPDATE_BRANCHES) args.push('--all');
    else if (scopeChoice === CUSTOM_UPDATE_BRANCH) {
      const branch = await askValidated(
        'EAS Update branch',
        '',
        'Enter the branch whose updates should be listed. A branch is the series of updates itself; a channel is the pointer a build follows to one.',
        validateRequiredText('Enter an EAS Update branch.'),
      );
      if (!branch) return undefined;
      args.push('--branch', branch);
    } else {
      args.push('--channel', scopeChoice.slice(CHANNEL_PREFIX.length));
    }
  }

  if (action.id === 'updates.insights') {
    const groupId = await askValidated(
      'EAS Update group ID',
      '',
      'Paste the update group ID to inspect adoption and crash metrics.',
      validateRequiredText('Enter an update group ID.'),
    );
    if (!groupId) return undefined;
    args.push(groupId);
  }

  /**
   * Offers the environments declared by the project's build profiles, plus an
   * escape hatch for one that is only defined on EAS.
   */
  const pickEnvironment = async (title: string): Promise<string | undefined> => {
    const environments = [
      ...new Set(project.buildProfiles.map((item) => item.environment).filter(Boolean)),
    ] as string[];
    const choice = await dashboard.pick(title, [
      ...(environments.length ? environments : ['production']).map((name) => ({
        label: name,
        value: name,
      })),
      { label: 'Enter another environment…', value: CUSTOM_ENVIRONMENT },
    ]);
    if (!choice) return undefined;
    return choice === CUSTOM_ENVIRONMENT
      ? askValidated(
          'EAS environment name',
          '',
          'Enter the exact EAS environment name.',
          validateRequiredText('Enter an environment name.'),
        )
      : choice;
  };

  if (action.id === 'updates.compare-fingerprint' && !action.interactive) {
    const environment = await pickEnvironment('Choose an EAS environment');
    if (!environment) return undefined;
    args.push('--environment', environment);
  }

  if (action.id === 'cloud.env') {
    // `eas env:list` takes the environment as a positional argument and cannot
    // prompt for it under CI, so it is collected here rather than left to fail.
    const environment = await pickEnvironment('Choose an EAS environment to list');
    if (!environment) return undefined;
    args.push(environment);
  }

  if (['account.usage', 'account.audit'].includes(action.id)) {
    const account = await askValidated(
      'Expo account name',
      '',
      'Enter the Expo account or organization name to query.',
      validateRequiredText('Enter an Expo account name.'),
    );
    if (!account) return undefined;
    args.push(account);
  }

  if (['release.metadata-pull', 'release.metadata-push'].includes(action.id)) {
    const profile = await pickProfile('Choose a submission profile', project.submitProfiles);
    if (!profile) return undefined;
    args.push('--profile', profile);
  }

  if (action.id === 'submissions.status') {
    const platform = await pickPlatform('Choose a submission platform', false);
    if (!platform) return undefined;
    const profile = await pickProfile('Choose a submission profile', project.submitProfiles);
    if (!profile) return undefined;
    args.push('--platform', platform, '--profile', profile);
  }

  if (action.id === 'release.store-setup') {
    const title = await askValidated(
      'App Store title',
      project.name,
      'This title is written to the local EAS Metadata configuration.',
      validateDisplayName,
    );
    if (!title) return undefined;
    const supportUrl = await askValidated(
      'Support website URL',
      '',
      'Required by store metadata.',
      validateUrl,
    );
    if (!supportUrl) return undefined;
    const privacyUrl = await askValidated(
      'Privacy policy URL',
      '',
      'Required by store metadata.',
      validateUrl,
    );
    if (!privacyUrl) return undefined;
    args.push('--title', title, '--support-url', supportUrl, '--privacy-url', privacyUrl);
  }
  return args;
}
