import * as fs from 'node:fs';
import * as path from 'node:path';

export interface BuildProfile {
  name: string;
  distribution?: string;
  channel?: string;
  environment?: string;
}

export interface ExpoProjectInfo {
  root: string;
  relativePath: string;
  name: string;
  slug?: string;
  sdkVersion?: string;
  expoVersion?: string;
  androidPackage?: string;
  iosBundleIdentifier?: string;
  projectId?: string;
  configFile?: string;
  hasGeneratedConfig: boolean;
  packageManager?: 'npm' | 'pnpm' | 'yarn' | 'bun';
  hasDependencies: boolean;
  hasEasConfig: boolean;
  hasStoreMetadata: boolean;
  hasUpdates: boolean;
  buildProfiles: BuildProfile[];
  submitProfiles: string[];
}

function readJson(filePath: string): Record<string, unknown> | undefined {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function firstExistingFile(root: string, names: string[]): string | undefined {
  return names.find((name) => fs.existsSync(path.join(root, name)));
}

/** The banner project-config.js writes at the top of a config it generated. */
const GENERATED_CONFIG_MARKER = 'Generated by Nova Expo Workflow Toolkit';

function isGeneratedConfig(root: string, configFile: string | undefined): boolean {
  if (!configFile || configFile === 'app.json') return false;
  try {
    return fs.readFileSync(path.join(root, configFile), 'utf8').includes(GENERATED_CONFIG_MARKER);
  } catch {
    return false;
  }
}

function packageManagerFor(root: string, workspaceRoot: string): ExpoProjectInfo['packageManager'] {
  let directory = root;
  const boundary = path.resolve(workspaceRoot);
  while (true) {
    if (fs.existsSync(path.join(directory, 'pnpm-lock.yaml'))) return 'pnpm';
    if (fs.existsSync(path.join(directory, 'yarn.lock'))) return 'yarn';
    if (
      fs.existsSync(path.join(directory, 'bun.lock')) ||
      fs.existsSync(path.join(directory, 'bun.lockb'))
    )
      return 'bun';
    if (fs.existsSync(path.join(directory, 'package-lock.json'))) return 'npm';
    if (directory === boundary || path.dirname(directory) === directory) return undefined;
    const parent = path.dirname(directory);
    if (path.relative(boundary, parent).startsWith('..')) return undefined;
    directory = parent;
  }
}

function hasInstalledDependencies(root: string, workspaceRoot: string): boolean {
  let directory = root;
  const boundary = path.resolve(workspaceRoot);
  while (true) {
    if (
      fs.existsSync(path.join(directory, 'node_modules', 'expo', 'package.json')) ||
      fs.existsSync(path.join(directory, 'node_modules', '.bin', 'expo')) ||
      fs.existsSync(path.join(directory, '.pnp.cjs')) ||
      fs.existsSync(path.join(directory, '.pnp.js'))
    )
      return true;
    if (directory === boundary || path.dirname(directory) === directory) return false;
    const parent = path.dirname(directory);
    if (path.relative(boundary, parent).startsWith('..')) return false;
    directory = parent;
  }
}

function sdkFromExpoVersion(version: string | undefined): string | undefined {
  if (!version) return undefined;
  const match = version.match(/(?:^|[^0-9])(\d{2})(?:\.|$)/);
  return match?.[1];
}

export function isExpoProjectRoot(root: string): boolean {
  const packageJson = readJson(path.join(root, 'package.json'));
  if (!packageJson) return false;
  const dependencies = asRecord(packageJson.dependencies);
  const devDependencies = asRecord(packageJson.devDependencies);
  return typeof dependencies?.expo === 'string' || typeof devDependencies?.expo === 'string';
}

export function readExpoProjectInfo(
  root: string,
  workspaceRoot = root,
): ExpoProjectInfo | undefined {
  const packageJson = readJson(path.join(root, 'package.json'));
  if (!packageJson) return undefined;

  const dependencies = asRecord(packageJson.dependencies);
  const devDependencies = asRecord(packageJson.devDependencies);
  const expoVersion =
    typeof dependencies?.expo === 'string'
      ? dependencies.expo
      : typeof devDependencies?.expo === 'string'
        ? devDependencies.expo
        : undefined;
  if (!expoVersion) return undefined;

  // Expo's own precedence: a dynamic config wins, and app.json is only the
  // static base it receives.
  const configFile = firstExistingFile(root, [
    'app.config.ts',
    'app.config.js',
    'app.config.mjs',
    'app.config.cjs',
    'app.json',
  ]);
  const appJson = readJson(path.join(root, 'app.json'));
  const expoConfig = asRecord(appJson?.expo) ?? appJson ?? {};

  const easJson = readJson(path.join(root, 'eas.json'));
  const buildProfilesRaw = asRecord(easJson?.build) ?? {};
  const submitProfilesRaw = asRecord(easJson?.submit) ?? {};
  const buildProfiles: BuildProfile[] = Object.entries(buildProfilesRaw).map(([name, value]) => {
    const profile = asRecord(value) ?? {};
    return {
      name,
      distribution: typeof profile.distribution === 'string' ? profile.distribution : undefined,
      channel: typeof profile.channel === 'string' ? profile.channel : undefined,
      environment: typeof profile.environment === 'string' ? profile.environment : undefined,
    };
  });

  const android = asRecord(expoConfig.android);
  const ios = asRecord(expoConfig.ios);
  const extra = asRecord(expoConfig.extra);
  const eas = asRecord(extra?.eas);
  const relativePath = path.relative(workspaceRoot, root) || '.';

  return {
    root,
    relativePath,
    name:
      typeof expoConfig.name === 'string'
        ? expoConfig.name
        : String(packageJson.name ?? 'Expo App'),
    slug: typeof expoConfig.slug === 'string' ? expoConfig.slug : undefined,
    sdkVersion:
      typeof expoConfig.sdkVersion === 'string'
        ? expoConfig.sdkVersion
        : sdkFromExpoVersion(expoVersion),
    expoVersion,
    androidPackage: typeof android?.package === 'string' ? android.package : undefined,
    iosBundleIdentifier:
      typeof ios?.bundleIdentifier === 'string' ? ios.bundleIdentifier : undefined,
    projectId: typeof eas?.projectId === 'string' ? eas.projectId : undefined,
    configFile,
    hasGeneratedConfig: isGeneratedConfig(root, configFile),
    packageManager: packageManagerFor(root, workspaceRoot),
    hasDependencies: hasInstalledDependencies(root, workspaceRoot),
    hasEasConfig: Boolean(easJson),
    hasStoreMetadata: fs.existsSync(path.join(root, 'store.config.json')),
    hasUpdates:
      typeof dependencies?.['expo-updates'] === 'string' ||
      typeof devDependencies?.['expo-updates'] === 'string',
    buildProfiles,
    submitProfiles: Object.keys(submitProfilesRaw),
  };
}
